### ISSUE TITLE
syntax error unexpected range, expecting {

### ISSUE THREAD

**Issue by Duality4Y** [limetext/lime-termbox#1]
Hi there,
I wanted to try out limetext and termbox,
so i followed the instructions here:
https://github.com/limetext/lime/wiki/Building-on-Ubuntu-14.04

when i got to the command:
go get github.com/limetext/lime-termbox/main/...
I got a few errors.
<code>
robert@Desktop:~/lime-termbox/main$ go get github.com/limetext/lime-termbox/main/...
github.com/limetext/lime-termbox/main
../../golang/src/github.com/limetext/lime-termbox/main/main.go:514: syntax error: unexpected range, expecting {
../../golang/src/github.com/limetext/lime-termbox/main/main.go:517: syntax error: unexpected }
../../golang/src/github.com/limetext/lime-termbox/main/main.go:592: syntax error: unexpected range, expecting {
../../golang/src/github.com/limetext/lime-termbox/main/main.go:595: syntax error: argument to go/defer must be function call
../../golang/src/github.com/limetext/lime-termbox/main/main.go:600: non-declaration statement outside function body
../../golang/src/github.com/limetext/lime-termbox/main/main.go:605: non-declaration statement outside function body
../../golang/src/github.com/limetext/lime-termbox/main/main.go:632: non-declaration statement outside function body
../../golang/src/github.com/limetext/lime-termbox/main/main.go:633: syntax error: unexpected }
</code>
So I did a little research and got here:
https://code.google.com/p/go/issues/detail?id=6102

I added to the range lines at 514  and 592 <code> _ = </code>
and now it builds.

I hope I was clear enough :)

also i just now got it to run.
awesome !

**Comment by erbridge** [comment]
You need `go1.4` or later to run Lime. They introduced a shorter `range` syntax for when you're not interested in the values.

**Comment by Duality4Y** [comment]
Oh i see :)
It seems that the go version in the ubuntu repositories is old,
maybe it should be noted somewhere which version you need.

**Comment by erbridge** [comment]
If you could update the wiki with instructions for getting `go1.4` working on Ubuntu, that would be really helpful (the requirement is mentioned in the table at the top of the page).

**Comment by Duality4Y** [comment]
I updated the wiki, I hope I did good :)

**Comment by erbridge** [comment]
Great. Thanks.
