### ISSUE TITLE
Last commit in limetext-backend breaks build of limettext-termbox

### ISSUE THREAD

**Issue by Bevaz** [limetext/lime-termbox#2]
Commit lime-backend/commit@0962c9d07442d3c758f9667c4e9b0e8375eb77b1 removed function Errorf(). This leads to compilation fail of limetext-termbox  here https://github.com/limetext/lime-termbox/search?utf8=%E2%9C%93&q=errorf

**Comment by zoli** [comment]
I think you mean [this commit](https://github.com/limetext/lime-backend/commit/0962c9d07442d3c758f9667c4e9b0e8375eb77b1) and you're right we should run frontend tests when we are making changes to lime-backend.
