### ISSUE TITLE
Debug messages all over the place

### ISSUE THREAD

**Issue by robertgzr** [limetext/lime-termbox#3]
This is what I get when I run `lime-termbox` (OSX10.9.5/ go1.5.!)

![screenshot](http://i.imgur.com/SKdpBqu.png)

When I resize the window it disappears...

**Comment by jdelgad** [comment]
I also get this running Ubuntu 15.10 on go 1.5.1.

**Comment by Theodus** [comment]
I have the same issue on Ubuntu 14.04 (Linux Mint 17.3) with Go 1.5.3

**Comment by erbridge** [comment]
Should be resolved by #6. Can someone confirm?
